### ISSUE TITLE
Session logged out when not requested

### ISSUE THREAD

**Issue by andriusign** [flathub/im.riot.Riot#490] opened 2024-11-19 13:36 UTC
### Steps to reproduce

1. Open Element. 
2. See start dialog as you are not logged in.

#### What did you expect?
Previous logged in session to be restored
#### What happened instead?
No old session, currently logged out

![image](https://github.com/user-attachments/assets/b22bcc4d-b598-4c70-8505-2c4a40bd4c52)

### Operating system

Linux Mint 21.3 Cinnamon 6.0.4, kernel 6.8.0-45-generic

### Application version

Element 1.11.85

### How did you install the app?

Via Software Center (flatpak version)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by andriusign** [comment] 2024-11-21 16:53
Any updates on this?

**Comment by SISheogorath** [comment] 2024-11-28 17:37
Duplicate of #481

**Closed by SISheogorath** 2024-11-28 17:37 UTC
