### ISSUE TITLE
Segmentation fault when maxsimising window

### ISSUE THREAD

**Issue by th1nhhdk** [flathub/im.riot.Riot#381] opened 2023-07-12 07:17 UTC
- Fedora 38
- KDE Plasma 5.27.6, running on Wayland
- Flatpak 1.15.4
- Element version: 1.11.35
- Olm version: 3.2.14

Element segmentation faults when maxsimising or tiling window, but for some reason resizing it doesn't crash.

```
[th1nhhdk@fedora ~]$ flatpak run im.riot.Riot
[3:0712/141534.814957:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
/home/th1nhhdk/.var/app/im.riot.Riot/config/Element exists: yes
/home/th1nhhdk/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
[3:0712/141535.544191:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0712/141535.544307:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Error getting the event index passphrase out of the secret store [Error: user interaction failed]
### after pressing maxsimise ###
/app/bin/element: line 16:     3 Segmentation fault      (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

**Comment by jkonecny12** [comment] 2023-07-14 09:03
I'm facing this issue too. Anyone has a solution or know more details about it?

I'm on Sway (tiling WM) so it's basically blocking me to use this application.

**Comment by jkonecny12** [comment] 2023-07-14 09:09
Last working SHA: 6b24295a5fa7e4e4c34177adf7c02d62947d46c1d6d048ef54b50367a1ba3ba7
Failure was introduced with: 9b6a4d7356134d33cc35c821ba70b8146ec1b7439a4ae234d1f451d7b4f8f4a5

Which has subject ` Update element-desktop-1.11.33.tar.gz to 1.11.34 (3bfc0949)`

**Comment by jkonecny12** [comment] 2023-07-14 09:13
Seems that this is a duplicate of https://github.com/flathub/im.riot.Riot/issues/376

**Comment by th1nhhdk** [comment] 2023-07-19 07:21
After upgrading to 1.11.36 the problem is still there

```
Element version: 1.11.36
Olm version: 3.2.14
```

```
[th1nhhdk@fedora ~]$ flatpak run im.riot.Riot 
[3:0719/141924.690985:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
/home/th1nhhdk/.var/app/im.riot.Riot/config/Element exists: yes
/home/th1nhhdk/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
[3:0719/141925.388117:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0719/141925.388210:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Error getting the event index passphrase out of the secret store [Error: user interaction failed]
[75:0100/000000.243303:ERROR:broker_posix.cc(41)] Recvmsg error: Connection reset by peer (104)
[75:0100/000000.244488:ERROR:broker_posix.cc(111)] Error sending sync broker message: Broken pipe (32)
/app/bin/element: line 16:     3 Segmentation fault      (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

**Comment by Szwendacz99** [comment] 2023-07-30 12:42
I was considering to return to the electron version of Element rather than chromium PWA, but I see the old weird bugs are still here.

**Comment by firefoxlover** [comment] 2023-08-28 21:05
For me, same OS (Fedora 38 KDE Kinoite, Wayland) it does crash

```
Fetching translation json for locale: de
Resetting the UI components after locale change
Error getting the event index passphrase out of the secret store [Error: user interaction failed]
/app/bin/element: Zeile 16:     3 Speicherzugriffsfehler  (Speicherabzug geschrieben) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

**Comment by pm4rcin** [comment] 2023-09-14 14:04
You should guys check the newest Element which has updated Electron to 26. It no longer crashes for me on sway. The same problem was present with Tutanota and they also updated Electron and issue is entirely gone. :)

**Closed** 2023-09-14 14:06 UTC
