### ISSUE TITLE
Intermittent hangs on launch: Zypak problem?

### ISSUE THREAD

**Issue by DemiMarie** [flathub/im.riot.Riot#152] opened 2020-12-18 00:09 UTC
When launching the flatpak, Riot hangs about 2/3 of the time.  A hard reload from Devtools fixes the problem.

I suspect the problem is related to Zypak.  Is there a way to test this?

**Comment by SISheogorath** [comment] 2020-12-18 12:01
@refi64 might has some ideas on that.

**Comment by refi64** [comment] 2020-12-20 00:26
The next Zypak version will have a fix for a potentially related issue, but it's worth noting IME this can happen if your connection is just spotty. In particular, I'd be interested to know if it's also reproducible with a standard Element installation.

**Comment by DemiMarie** [comment] 2020-12-20 00:59
@refi64 It is not.

**Comment by refi64** [comment] 2020-12-20 18:05
This bundle should have a build of Element with the latest Zypak: https://drive.google.com/file/d/1GzUX05TIgIS0twj6puGpaGArhyWnVnPO/view?usp=sharing

Can you try it and see if that one works?

**Comment by DemiMarie** [comment] 2020-12-20 19:56
@refi64 sorry, but I don’t run bundles that aren’t signed by a key I trust.  I have no reason to believe that your bundle is malicious, but I would prefer to not take any chances.  Thanks for the offer, though!  It isn’t personal, just me being careful.

**Comment by refi64** [comment] 2020-12-20 20:00
Understandable, see #153.

**Comment by DemiMarie** [comment] 2020-12-21 03:02
> The next Zypak version will have a fix for a potentially related issue, but it's worth noting IME this can happen if your connection is just spotty. In particular, I'd be interested to know if it's also reproducible with a standard Riot/Element installation.

Which commit is this?

**Comment by vchernin** [comment] 2021-06-17 19:11
@DemiMarie It looks like the changes that were tested in #153 are in recent builds of zypak. Is this fixed in flathub stable now? Then we can close this.

**Comment by Yajo** [comment] 2021-11-05 07:23
Is this issue somehow related to https://github.com/vector-im/element-web/issues/18625? That one's bugging me all the time...

**Comment by DemiMarie** [comment] 2021-11-05 08:25
@Yajo Probably not; this one was fixed a while back if I recall correctly.  @vchernin go ahead and close this.

**Comment by SISheogorath** [comment] 2021-11-05 15:27
If this was fixed, we should close this issue.

**Closed** 2021-11-05 16:23 UTC
Labels: bug
