### ISSUE TITLE
Host CA are not used

### ISSUE THREAD

**Issue by ficoos** [flathub/im.riot.Riot#28] opened 2019-01-27 15:50 UTC
Custom CAs are not taken from the host. There is no other way to add a CA to the sandbox. This means that self signed home servers can't be used.

**Comment by TingPing** [comment] 2019-01-27 20:54
This is something to discuss over at flatpak/flatpak.

The problem is openssl as for gnutls it should just work.

**Comment by LorbusChris** [comment] 2019-02-08 17:03
I had hoped this would be fixed by the latest p11-kit release, which is now in the 18.08 base, but it wasn't :(

**Comment by Erick555** [comment] 2019-04-01 19:01
@LorbusChris firefox should be potentially fixed by https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/1145 (not in flathub yet). I don't know about riot.

**Comment by SISheogorath** [comment] 2019-10-07 18:20
Is this solved by the mentioned feature above being merged?

**Comment by TingPing** [comment] 2019-10-07 19:54
Riot uses Electron which has a bundled fork of OpenSSL, it is not in any way affected by that NSS patch.

**Comment by SISheogorath** [comment] 2019-10-07 19:57
@TingPing wouldn't it makes sense to mount the host's CA directory as read-only into the runtime? (Which would me this issue would also be addressed on a lower level)

**Comment by TingPing** [comment] 2019-10-07 20:09
My very first comment was "This is something to discuss over at flatpak/flatpak." and that remains the case.

This isn't a package issue. Perhaps you are right that we can safely pass them into the sandbox. I don't know and it needs discussion.

**Comment by LorbusChris** [comment] 2019-10-08 16:23
I created an issue for this upstream some time ago: https://github.com/flatpak/flatpak/issues/2721

**Comment by SISheogorath** [comment] 2019-10-08 22:17
Then let's close it on the app level. People should be able to find the issue upstream from here :)

**Closed by SISheogorath** 2019-10-08 22:17 UTC
Labels: enhancement
