### ISSUE TITLE
Tray icon is broken

### ISSUE THREAD

**Issue by ananace** [flathub/im.riot.Riot#3] opened 2017-11-20 15:25 UTC
As pictured on KDE Plasma 5.11.2

![screenshot_20171120_162432](https://user-images.githubusercontent.com/534460/33025841-4dcee85c-ce0f-11e7-8696-f3623f1e9785.png)

**Comment by Barthalion** [comment] 2017-11-20 15:49
Works fine under Gnome. Any KDE magicians would like to chime in? @aleixpol @gruija

**Comment by aleixpol** [comment] 2017-11-20 17:28
Can you please provide some more information on how to reproduce it? What's the application? is it on flathub?

**Comment by Barthalion** [comment] 2017-11-20 20:52
Yeah, it's `im.riot.Riot` on Flathub.

**Comment by ace13** [comment] 2017-11-20 21:09
It's possible that it's possible that it's something to do with lacking the right icon sizes? That could explore the difference between Gnome  and KDE

**Comment by grulja** [comment] 2017-11-21 09:15
Briefly looking into KStatusNotifierItem (framework for providing tray icon in KDE) and it needs smaller icon size for system tray, specifically 24x24. That might be the reason why this is not working under KDE. This is easily reproducible and works when you run "XDG_CURRENT_DESKTOP=GNOME flatpak run im.riot.Riot" which forces Qt to use different platform theme which uses different implementation for tray icons.

**Comment by ace13** [comment] 2017-11-21 09:20
So perhaps it's something to get upstream to fix?

I imagine that doing a downscale of the large icon might be a good quick fix until then though?

**Comment by aleixpol** [comment] 2017-12-15 17:25
@grulja we shouldn't be asking plasma users to force `XDG_CURRENT_DESKTOP=GNOME` by any means, that's broken.

If you guys can give me an easy way to reproduce it locally I can put together a fix. It's not nice that we enforce 24px icons anyway, if it's not part of the spec.

**Comment by grulja** [comment] 2017-12-18 06:18
@aleixpol I wasn't suggesting that, I used it just as a prove that the problem is on our side.

**Comment by nedrichards** [comment] 2018-01-25 18:34
We're now exporting 24x24px icons @ace13 can you test again?

**Comment by all-the-good-ones-are-gone** [comment] 2018-01-26 10:38
I've just pulled the new riot, closed and opened the program to no change:
Ref: app/im.riot.Riot/x86_64/stable
ID: im.riot.Riot
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2018-01-25 17:05:00 +0000
Subject: All icon sizes, more comprehensive appdata, desktop fix (71f8531e)
Commit: 0746e7231e20c0b54dc1b3c2d41a1a9858165be86e838c35d64b59384538fd96
Parent: a1d5d9e46b197b69aaa92ea442ad31f5a674874ae5940d8ee58cbf50c7b119b3
Location: /var/lib/flatpak/app/im.riot.Riot/x86_64/stable/0746e7231e20c0b54dc1b3c2d41a1a9858165be86e838c35d64b59384538fd96
Installed size: 219.6 MB
Runtime: org.freedesktop.Platform/x86_64/1.6

Plasma 5.11.95

Do I need to log out, or purge and reinstall?

**Comment by ace13** [comment] 2018-01-26 19:29
I had an icon (With the wrong size, but still an icon) for a short period after starting it on the new version, but it seems like Riot changes the tray icon depending on state so it went right back to a missing icon after it had synced initial state.

**Comment by all-the-good-ones-are-gone** [comment] 2018-01-28 12:48
Yes, when I first open I get a purple almost-rectangle, looking to be the top left portion of the dot in the i (there's a little bit of green the the corner), then it changes to the broken image icon again.
https://i.imgur.com/MJl11mz.png

**Comment by nedrichards** [comment] 2018-02-01 21:32
Didn't mean to close this - that change may fix it by making sure that the normal riot-web icons aren't renamed but copied.

**Comment by ananace** [comment] 2018-02-09 18:54
Even with that fix in place the same issue still exists, maybe it's time for me to break out the debugging tools, see if I can find just what's going on with the icon lookup for the tray.

**Comment by ananace** [comment] 2018-05-21 12:35
I just noticed today that I seem to have a working Riot icon in my tray all of a sudden;

```
Ref: app/im.riot.Riot/x86_64/stable
ID: im.riot.Riot
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2018-05-20 10:04:57 +0000
Subject: Update to 0.15.3 (8df33d90)
Commit: 9d99fc5c1498ef988596b673f478faa723d98b821ef19e20982453b64b4d57fc
Parent: 25304d09e47e5338993a9050f5b63dc06c3c0adffb34f70da865b01874a5cdbe
Location: /home/ace/.local/share/flatpak/app/im.riot.Riot/x86_64/stable/9d99fc5c1498ef988596b673f478faa723d98b821ef19e20982453b64b4d57fc
Installed size: 219,3 MB
Runtime: org.freedesktop.Platform/x86_64/1.6
```

![screenshot_20180521_142950](https://user-images.githubusercontent.com/534460/40307593-6eaaf3e4-5d03-11e8-9641-8a51b1e7b7af.png)

Fixed on the application side? Or something fixed in Plasma 5.12.5? Qt 5.9.5? Flatpak 0.11.7?

**Comment by nedrichards** [comment] 2018-05-21 12:39
Likely a combo of application and plasma - glad to hear it!

**Comment by all-the-good-ones-are-gone** [comment] 2018-05-22 10:43
Can confirm.

Ran updates, modified my ~/.config/autostart/im.riot.Riot.desktop to remove "XDG_CURRENT_DESKTOP=GNOME " from the beginning of the launch, and after reboot I have (a little fuzzy) icon that has different actions when you left and right click it.

For some reason the file didn't launch on login.... will have to play with that.

**Comment by all-the-good-ones-are-gone** [comment] 2018-05-26 02:45
@Fantastitech Everything looks good here:
KDE Plasma Version: 5.12.5
KDE Frameworks Version: 5.46.0
Qt Version: 5.10.0
Kernel Version: 4.16.10-1-default
Riot version: 0.15.3 (8df33d90) from im.riot.Riot on flathub

The icon looks a little fuzzy, but otherwise behaves normal.

In this case, maybe it's somehow related to newer kernel? Or difference between openSUSE and ?Ubuntu? libraries?

**Comment by uhoreg** [comment] 2018-07-14 01:38
Riot in general has some issues with the tray icon.  See https://github.com/vector-im/riot-web/issues/3133.  So having the icon fuzzy, or just a purple square, is probably a Riot issue, and not an issue with the flatpak image.

**Comment by fbruetting** [comment] 2019-02-01 14:46
For me under Gnome 3.30 (Fedora Silverblue) it looks like this:

![bildschirmfoto von 2019-02-01 15-45-27](https://user-images.githubusercontent.com/10520767/52129719-843b1780-2638-11e9-91ac-83bea1397f7a.png)

**Comment by SISheogorath** [comment] 2019-09-20 22:27
Any changes in this recently?

**Comment by fbruetting** [comment] 2019-12-06 23:07
For me it now works fine!

**Closed** 2020-05-22 15:37 UTC
Labels: bug
