### ISSUE TITLE
Endless spinner after upgrade to 1.11.23, element no longer usable (also, crashes)

### ISSUE THREAD

**Issue by ell1e** [flathub/im.riot.Riot#345] opened 2023-03-03 23:22 UTC
After the upgrade to 1.11.23 I terminated the old element and made sure no `element-desktop` was left running, launched it again, and now I'm getting an endless spinner. I've been letting it sit for like ten minutes now with nothing happening now so it seems like element is no longer usable since it just won't proceed to an operational state. I also previously had a normal mouse cursor and now I'm seeing #341 if that gives you an idea what my old version was, sadly I didn't write it down.

**Comment by ell1e** [comment] 2023-03-04 11:22
So how do I work around this? I left it running overnight now, many hours, still spinner with absolutely no indication what it is even doing.

**Comment by ell1e** [comment] 2023-03-05 13:15
I wiped `~/.var/app/im.riot.Riot` now, started fresh, *then it crashed a few minuites in* and after restarting endless spinner again. Something is very broken with this flatpak release. Element web ran for days just fine while this situation was evolving.

**Comment by ell1e** [comment] 2023-03-05 13:32
Just repeated it, oof.

Wouldn't it make sense to package an older version that actually works? Until all these bugs are sorted out that render it unusable.

**Comment by LorbusChris** [comment] 2023-03-06 09:45
Dupe of https://github.com/flathub/im.riot.Riot/issues/339?

**Comment by ell1e** [comment] 2023-03-06 10:01
That doesn't include the endless spinner issue, which by the way was *not* originally caused by this crash. It just happened after a normal shutdown of the upgrade.

**Comment by andypillip** [comment] 2023-06-04 11:11
I’ve been seeing this endless spinner for quite a while now, too.

**Comment by andypillip** [comment] 2023-06-04 11:32
I could fix it by deleting all Cache files in `.var/app/im.riot.Riot/config/Element/Cache/Cache_Data/`.

**Closed** 2023-11-18 17:24 UTC
