### ISSUE TITLE
No tray icon

### ISSUE THREAD

**Issue by pwr22** [flathub/im.riot.Riot#100] opened 2020-05-06 11:15 UTC
Seen on both Manjaro with AwesomeWM and Ubuntu 20.04 with Gnome so I don't think it's a desktop environment issue.

**Comment by Erick555** [comment] 2020-05-06 12:35
It worked on kde before 1.6.x. Does it still work on non-flatpak riot?

**Comment by pwr22** [comment] 2020-05-06 12:39
Yes

**Comment by SISheogorath** [comment] 2020-05-06 13:20
Is it just recently, that it's missing or was it missing in other releases as well?

**Comment by Erick555** [comment] 2020-05-06 13:45
For me it worked in KDE before 1.6

**Comment by pwr22** [comment] 2020-05-06 13:48
I believe this may coincide with a change from electron 7 to electron 8 which does away with xembed support :thinking: .

**Comment by Erick555** [comment] 2020-05-06 14:06
To make things worse now I can't exit this app properly from gui. Closing window always left the process running for me and I had to quit it from the tray. Now I have to kill the app process manually.

**Comment by Erick555** [comment] 2020-05-06 14:16
Adding `--own-name=org.kde.StatusNotifierItem-2-1` permission fixes this for me however this may differ among host environments and `--own-name=org.kde.*` may be needed instead.

https://github.com/flathub/us.zoom.Zoom/commit/348ff4e59ac6cc8104a729710dd11dba67147f51

https://github.com/flathub/com.dropbox.Client/commit/a0594d16997f6f9c65919d0c8afd056137737957

**Comment by pwr22** [comment] 2020-05-06 14:20
alt+q should quit it completely

Thanks,

Peter

**Comment by pwr22** [comment] 2020-05-06 14:28
Where do I need to add these flags?

Thanks,

Peter

**Comment by SISheogorath** [comment] 2020-05-06 14:50
@pwr22 you can use `flatpak override --user --own-name=org.kde.StatusNotifierItem-2-1 im.riot.Riot` to test this changes. They are applied after restarting the Riot in Flatpak.

Generally speaking, I'm not a fan of the idea putting `--own-name=org.kde.*` anywhere.

**Comment by SISheogorath** [comment] 2020-05-06 19:43
Since the question came up multiple times in the Riot support chat, I came across [the info](https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$xSOdy7v9Bu3SGHFgQm98OH0uROsN4e5k-5bPYYA9O-I?via=matrix.org&via=privacytools.io&via=mozilla.org) that the new version of Riot runs on a new electron version, which is using a new chrome version, that dropped support for `xembed`.

The integration now has to support `sni/libappindicator`. One solution is [this GNOME extension](https://extensions.gnome.org/extension/615/appindicator-support/) which supports libappindicator. Which was [verified to be working](https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$7cGeyeuFcDSalNGI-VKxgTs6i1_XYssqNpTyJHpfJNY?via=matrix.org&via=privacytools.io&via=mozilla.org). So it doesn't seem to be a flatpak problem on its own.

**Comment by gasinvein** [comment] 2020-05-06 19:48
`--own-name=org.kde.StatusNotifierItem-2-1` is fine as long as you have exactly one flatpak app using it.

What changed in recent update, why did it work fine before?

**Comment by LiohMoeller** [comment] 2020-05-07 06:13
The override does not work for me on IceWM. Is there a way to remove the override again? Also Alt+Q does not work to quit the application. So if I close it, it's still running in the background.

**Comment by LinAGKar** [comment] 2020-05-07 08:08
@LiohMoeller, ctrl+q worked for me to quit it.

@gasinvein, Summing up the issue as far as I've understood it. The issue started happening due to an update to Electron, which switched from xembed, to SNI. This led to two different problems:
- SNI doesn't work in some DEs by default. It works in KDE and Unity, but not in e.g. GNOME, or presumably IceWM. The [AppIndicator Support GNOME extension](https://extensions.gnome.org/extension/615/appindicator-support/) is suggested to fix this on GNOME. Not sure about other DEs.
- Flatpak does not currently let the application own a D-BUS name it needs in order to use SNI. `flatpak override --own-name=org.kde.StatusNotifierItem-2-1 im.riot.Riot` is used as a workaround for this.

**Comment by MatMaul** [comment] 2020-05-07 09:39
Even with the Gnome plugin and the own dbus permission, the tray icon disappears after a screen lock :( 
This one is unrelated to Flatpak however, it's a known problem with Electron and even Chromium on Gnome with the appindicator plugin.
https://github.com/electron/electron/issues/22443
https://bugs.chromium.org/p/chromium/issues/detail?id=1042098

**Comment by gasinvein** [comment] 2020-05-07 09:47
@LinAGKar I'm using appindicator-support extension on Gnome and I'm pretty sure Riot used it for it's tray icon on my machine.

**Comment by MatMaul** [comment] 2020-05-07 09:59
I don't see any reasonable workaround outside of packaging and launching snixembed until it got solved. Thought ?
https://git.sr.ht/~steef/snixembed

**Comment by gasinvein** [comment] 2020-05-07 10:12
@MatMaul Quick look into it gives me impression that it won't help, just snixembed will need to own the SNI dbus name instead of the application.

**Comment by MatMaul** [comment] 2020-05-07 10:22
:( right I forgot that we don't have a private dbus session in the jail, it's just an ACL'd proxy.
:cry: 
I'll install that on my host then.

**Comment by pwr22** [comment] 2020-05-07 10:35
We need the override to let dbus out from the flatpak and if the desktop
environment doesn't support anything but xembed (like AwesomeWM) then we
also need snixembed.

**Comment by mfilipe** [comment] 2020-05-07 14:05
fedora-32 riot-1.6.0 flatpak is having the same problem.

**Comment by MatMaul** [comment] 2020-05-07 14:33
The problem is that the override is pretty bad in the end, since it will only allow one electron app to use the tray, after that it will try to own the same dbus object (high chances of same pid 2 since they are pid-namespaced) and fails. It needs proper support in Flatpak itself I think, probably some mapping between object names in the proxy. I'll open a bug later on Flatpak side during the weekend, I can't find an existing one when searching `StatusNotifierWatcher`.

**Comment by Erick555** [comment] 2020-05-07 14:35
I believe there is opened bug for this somewhere although I can't find it right now. The conclusion was this needs patch in kde/qt not in flatpak.

**Comment by MatMaul** [comment] 2020-05-07 14:38
Hum. I am failing to see the direct relation with KDE/Qt, so if you find it I am interested.

**Comment by Erick555** [comment] 2020-05-07 15:37
The supposedly control the specification:

https://github.com/flathub/com.dropbox.Client/pull/17#discussion_r224631854

https://github.com/flathub/com.borgbase.Vorta/issues/19#issuecomment-614408836

**Comment by foresto** [comment] 2020-05-07 18:47
>     * SNI doesn't work in some DEs by default. It works in KDE and Unity, but not in e.g. GNOME, XFCE, or presumably IceWM.

For the record, a [Status Notifier panel plugin](https://docs.xfce.org/panel-plugins/xfce4-statusnotifier-plugin) is available for current versions of Xfce. I have both it and the Notification Area panel plugins on Xubuntu 19.10. (Sadly, this alone doesn't solve the problem; my Riot tray icon disappeared, too.)

**Comment by LiohMoeller** [comment] 2020-05-07 20:47
For me it works on IceWM by running snixembed --fork during X startup. The disadvantage is that it also embeds other application icons like Nextcloud or Owncloud and makes them look really ugly (too big, cut off, distorted)

**Comment by paddyesch** [comment] 2020-05-07 21:52
I can confirm this issue for Ubuntu 19.10 with Riot 1.6.0 flatpak and Ubuntu appindicators extension enabled.

**Comment by MatMaul** [comment] 2020-05-08 09:09
@Erick555 thanks. What a mess...
Seems like most software are doing `--own-name=org.kde.*` for now so we should probably do the same here.

**Comment by MatMaul** [comment] 2020-05-08 12:20
Related to the second problem with the tray disappearing on lock/unlock, I post what I understood of it in this Electron bug: https://github.com/electron/electron/issues/22443

**Comment by SISheogorath** [comment] 2020-05-08 12:42
@MatMaul especially because most software currently goes for that, we shouldn't. It makes conflicts even more likely. And I'm not a fan of this idea. I'm more looking towards disabling the tray-icon by default, which would at least solve the "the app is closed but continues to run in background"-problem, or just leave it as it is and people have to set things themselves using flatpak override.

If we find a single dbus name we should own, that might also be an option, but I'm not sure if we can do this. I'm strongly opposing to own the entire kde namespace.

**Comment by MatMaul** [comment] 2020-05-08 12:53
I understand, but we let some other apps do it so Riot seems to get special treatment here ^^
The proper way (outside of changing the spec, and push all the apps using it to change afterwards, which probably means in 2 years ^^) I can see is to deal with that in the proxy, and rewrite the object name on the fly.
For people that have more D-Bus knowledge than me, is it even possible on the principle or some stuff I don't understand would break because of a renamed object in the proxy ?

**Comment by anon88391** [comment] 2020-05-08 21:21
Experiencing the same thing after updating Riot to 1.6.0 on newest Debian Buster with Xfce.

**Comment by Erick555** [comment] 2020-05-11 12:16
> especially because most software currently goes for that, we shouldn't. It makes conflicts even more likely.

Note that in case of conflict, the tray just won't work for apps that tried to own same dbus address beside the first one launched so this isn't worse than not having tray at all.

I recommend to add` --own-name=org.kde.StatusNotifierItem-2-1` in manifest for now.

**Comment by SISheogorath** [comment] 2020-05-11 16:42
@Erick555 I see, that makes sense. Then let's do this :)

**Comment by SISheogorath** [comment] 2020-05-11 17:10
To all people who experience the issue, please try to verify that it works with this build:
https://github.com/flathub/im.riot.Riot/pull/104#issuecomment-626830369

**Comment by mfilipe** [comment] 2020-05-11 17:55
> To all people who experience the issue, please try to verify that it works with this build:
> [#104 (comment)](https://github.com/flathub/im.riot.Riot/pull/104#issuecomment-626830369)

Fedora 32 with Ubuntu appindicators extension enabled, it works.

**Comment by foresto** [comment] 2020-05-11 18:17
> To all people who experience the issue, please try to verify that it works with this build:

Isn't the fix in that build only for KDE? I experience the issue on Xfce. Is there any reason to think it would help there?

**Comment by Erick555** [comment] 2020-05-11 20:34
It certailny work for KDE and GNOME (with extension).

[This comment](https://github.com/flathub/im.riot.Riot/issues/100#issuecomment-625100119) suggests it will work also with XFCE if Status Notifier Plugin is installed.

**Comment by foresto** [comment] 2020-05-11 21:44
> This comment suggests it will work also with XFCE if Status Notifier Plugin is installed.

I confirmed this myself just now. Thanks.

**Closed** 2020-05-11 21:47 UTC
Labels: bug

**Comment by foresto** [comment] 2020-05-12 06:58
I just noticed that (in Xfce) single-left-click on the tray icon finally shows/hides the Riot window. Hooray! I guess this fix must have come from the new Electron version?

**Comment by SISheogorath** [comment] 2020-05-12 19:27
We haven't changed anything else than the permissions since I merged #104, so no, that was not due to any electron update.

**Comment by foresto** [comment] 2020-05-12 19:44
Maybe it was fixed by something in the riot executable or Electron2.BaseApp, then. (I updated all my flatpaks at the same time.) Whatever the cause, having left-click work correctly is a nice improvement.

**Comment by LinAGKar** [comment] 2020-05-12 20:02
> I just noticed that (in Xfce) single-left-click on the tray icon finally shows/hides the Riot window. Hooray! I guess this fix must have come from the new Electron version?

That's probably due to the switch from xembed to SNI. That same happened on KDE.

**Comment by thomassross** [comment] 2020-05-25 15:35
In my case, for whatever reason, the required bus is named `org.kde.StatusNotifierItem-3-1`. I'm not sure why it's named differently, but you can find out what yours is named by using D-Feet or similar and searching for session buses named similar to `org.kde.StatusNotifierItem` and allowing Riot to use them with `flatpak --user override im.riot.Riot --own-name=org.kde.StatusNotifierItem-3-1`.

I'm not sure what the general fix is, allowing Riot to own any name matching `org.kde.*` works but is definitely not an ideal solution.

**Comment by vladimiry** [comment] 2020-05-26 17:45
By the way, it turned out Electron is getting rid of DBus related tray icon implementation rolled out with @chromium update in Electron v8 in favor of previously used / `GTK/appindicator` approach, see electron/electron#23674.
